export const ACTIONS = Object.freeze({
    DEBUG: true,
    CLICKED_BROWSER_ACTION: 'CLICKED_BROWSER_ACTION',
    TAB_URL_UPDATED: 'TAB_URL_UPDATED',
    GET_PLAYLIST_DATA_FROM_LOCAL_STORAGE:
        'GET_PLAYLIST_DATA_FROM_LOCAL_STORAGE',
    GET_PLAYLIST_DATA_FROM_LOCAL_STORAGE_SUCCESS:
        'GET_PLAYLIST_DATA_FROM_LOCAL_STORAGE_SUCCESS',
    GET_PLAYLIST_DATA_FROM_LOCAL_STORAGE_ERROR:
        'GET_PLAYLIST_DATA_FROM_LOCAL_STORAGE_ERROR',
    FETCH_ARCHIVED_PLAYLIST_DATA: 'FETCH_ARCHIVED_PLAYLIST_DATA',
    FETCH_ARCHIVED_PLAYLIST_DATA_SUCCESS:
        'FETCH_ARCHIVED_PLAYLIST_DATA_SUCCESS',
    FETCH_ARCHIVED_PLAYLIST_DATA_ERROR: 'FETCH_ARCHIVED_PLAYLIST_DATA_ERROR',
    FETCH_WEB_SEARCHED_PLAYLIST_DATA: 'FETCH_WEB_SEARCHED_PLAYLIST_DATA',
    FETCH_WEB_SEARCHED_PLAYLIST_DATA_SUCCESS:
        'FETCH_WEB_SEARCHED_PLAYLIST_DATA_SUCCESS',
    FETCH_WEB_SEARCHED_PLAYLIST_DATA_ERROR:
        'FETCH_WEB_SEARCHED_PLAYLIST_DATA_ERROR',
    STORE_PLAYLIST_DATA: 'STORE_PLAYLIST_DATA',
    STORE_PLAYLIST_DATA_SUCCESS: 'STORE_PLAYLIST_DATA_SUCCESS',
    STORE_PLAYLIST_DATA_ERROR: 'STORE_PLAYLIST_DATA_ERROR',
    REDIRECT_TO_URL: 'REDIRECT_TO_URL',
    REDIRECT_TO_URL_SUCCESS: 'REDIRECT_TO_URL_SUCCESS',
    REDIRECT_TO_URL_ERROR: 'REDIRECT_TO_URL_ERROR',
})
